export interface Employee {
    _id: string,
    name: string,
    department: string,
    position: string,
    email: string,
    phone: number,
    birthday: string,
    location: string,
    homeAddress: string,
    hireOn: string,
    hours: string,
    createdAt: string,
    updatedAt: string,
}